#Dependecias
FROM node:22-alpine3.23 AS deps
WORKDIR /usr/src/app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install --frozen-lockfile

#   Builder
FROM node:22-alpine3.23 AS builder
WORKDIR /usr/src/app

# copiar de deps los modulos de node
COPY --from=deps /usr/src/app/node_modules ./node_modules

# copiar todo el código fuente de la aplicación 
COPY . .
ENV PORT=3000
ENV DATABASE_URL="file:/usr/src/app/data/prod.db"
ENV NATS_SERVERS="nats://localhost:4223"
# RUN yarn run test
RUN yarn prisma generate
RUN yarn build

RUN yarn install --frozen-lockfile --production && yarn cache clean


#   Crear la imagen de producción
FROM node:22-alpine3.23 AS prod
# Install openssl for runtime
RUN apk add --no-cache openssl
WORKDIR /usr/src/app    

ENV NODE_ENV=production
ENV PORT=3000
ENV DATABASE_URL="file:/usr/src/app/data/prod.db"
ENV NATS_SERVERS="nats://localhost:4223"

COPY --from=builder /usr/src/app/node_modules ./node_modules
# copiar la carpeta de DIST 
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/prisma ./prisma
COPY --from=builder /usr/src/app/prisma.config.ts ./ 

USER root
RUN mkdir -p /usr/src/app/data && chown -R node:node /usr/src/app/data
USER node

EXPOSE 3000

CMD [ "sh", "-c", "DATABASE_URL=$DATABASE_URL npx prisma migrate deploy && node dist/main.js" ]